### ISSUE TITLE
怎么获取poe的API token

### ISSUE THREAD

**Issue by qingyanbaby** [formzs/poe-gpt-api#2]
我在官网只有机器人对话，个人信息设置这些，没看到有api token相关的信息

**Comment by qingyanbaby** [comment]
我是订阅了的

**Comment by formzs** [comment]
> [qingyanbaby](/qingyanbaby)

试一下：[https://poe.com/api_key](https://poe.com/api_key)

**Comment by qingyanbaby** [comment]
> > [qingyanbaby](/qingyanbaby)
> 
> 试一下：https://poe.com/api_key

可以。官方页面也入口
